format_version: 10
pipelines:
  test_pipeline:
    group: testGroup
    materials:
      git_repo:
        type: git
        attributes:
          url: https://github.com/example/repo.git
    stages:
      - name: TestStage
        jobs:
          - name: TestJob
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Testing"
