format_version: 10
pipelines:
  your_pipeline_demo:
    group: defaultGroup
    materials:
      your_material_name:
        type: git
        attributes:
          url: https://github.com/shubhamdeshpande1997/testinng.git
          branch: main
          username: "{{SECRET_USERNAME}}"
          password: "{{SECRET_PASSWORD}}"
    stages:
      - name: Build
        jobs:
          - name: HelloWorld
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Hello, world!"
