format_version: 10
pipelines:
  your_pipeline_demo:
    group: defaultGroup
    materials:
      git_repo:
        type: git
        attributes:
          url: https://github.com/shubhamdeshpande1997/testinng.git
          branch: main
    stages:
      - name: Build
        jobs:
          - name: HelloWorld
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Hello, world!"
