format_version: 2
pipelines:
  your_pipeline_demo:
    group: defaultGroup
    materials:
      your_material_name:
        type: git
        attributes:
          url: https://github.com/shubhamdeshpande1997/testinng.git
          branch: main
          username: shubhamdeshpande1997
          password: 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
    stages:
      - stage: Build
        jobs:
          - job: HelloWorld
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Hello, world!"
